#!/bin/env bash
HOSTS_FILE="/etc/hosts"
sudo sed -i '/localhost/d' "$HOSTS_FILE"
sudo sed -i '/facebook.com/d' "$HOSTS_FILE"
echo "127.0.0.2 localhost" | sudo tee -a "$HOSTS_FILE" > /dev/null
echo "8.8.8.8 facebook.com" | sudo tee -a "$HOSTS_FILE" > /dev/null
